apiVersion: v1
kind: PersistentVolume
metadata:
  name: quotes-db-pv
spec:
  capacity:
    storage: 1Gi  # Adjust the storage size as needed
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/quotes-db  # Path on the host machine where the data will be stored
