apiVersion: v1
kind: Pod
metadata:
  name: mainpage-api
  labels:
    app: mainpage-api
spec:
  containers:
  - name: mainpage-api-container
    image: clusterminator/mainpage-api:1.0
    ports:
    - containerPort: 8080